apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db-demo
  template:
    metadata:
      labels:
        app: db-demo
    spec:
      containers:
      - name: db-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80