receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:
    send_batch_size: 8192
    timeout: 5s
    send_batch_max_size: 10240
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection:
    detectors: [env, docker]
    override: true
  transform/sanitize_logs:
    error_mode: ignore
    log_statements:
      - context: scope
        statements:
          - set(attributes["otelcol_signal"], attributes["otelcol.signal"]) where attributes["otelcol.signal"] != nil and not IsMap(attributes["otelcol.signal"])
          - delete_key(attributes, "otelcol.signal") where attributes["otelcol_signal"] != nil
  transform/sanitize_spans:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(span.attributes["http.route"], "/api/cart") where span.kind == SPAN_KIND_SERVER and resource.attributes["service.name"] == "frontend" and span.attributes["http.route"] == nil and IsMatch(span.attributes["http.target"], "\\/api\\/cart")
          - set(span.attributes["http.route"], "/api/checkout") where span.kind == SPAN_KIND_SERVER and resource.attributes["service.name"] == "frontend" and span.attributes["http.route"] == nil and IsMatch(span.attributes["http.target"], "\\/api\\/checkout")
          - set(span.attributes["http.route"], "/api/products/{productId}") where span.kind == SPAN_KIND_SERVER and resource.attributes["service.name"] == "frontend" and span.attributes["http.route"] == nil and IsMatch(span.attributes["http.target"], "\\/api\\/products\\/.*")
          - set(span.attributes["http.route"], "/api/recommendations") where span.kind == SPAN_KIND_SERVER and resource.attributes["service.name"] == "frontend" and span.attributes["http.route"] == nil and IsMatch(span.attributes["http.target"], "\\/api\\/recommendations")
          - set(span.attributes["http.route"], "/api/data") where span.kind == SPAN_KIND_SERVER and resource.attributes["service.name"] == "frontend" and span.attributes["http.route"] == nil and IsMatch(span.attributes["http.target"], "\\/api\\/data.*")
          - set_semconv_span_name("1.37.0", "original_span_name")

exporters:
  debug:
  otlp/newrelic:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${NEW_RELIC_API_KEY}
    tls:
      insecure: false

connectors:
  span_metrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, transform/sanitize_spans, batch]
      exporters: [debug, span_metrics, otlp/newrelic]
    metrics:
      receivers: [otlp, span_metrics]
      processors: [resourcedetection, memory_limiter, batch]
      exporters: [debug, otlp/newrelic]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, transform/sanitize_logs, batch]
      exporters: [debug, otlp/newrelic]