receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp_http/newrelic:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: YOUR_NEW_RELIC_LICENSE_KEY

  otlp_grpc/newrelic:
    endpoint: otlp.nr-data.net:4317
    headers:
      api-key: YOUR_NEW_RELIC_LICENSE_KEY

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_http/newrelic
        - otlp_grpc/newrelic

    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_http/newrelic

    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_http/newrelic