name: Ping URLs
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours (at 0:00, 6:00, 12:00, 18:00 UTC)
  workflow_dispatch: # Allows manual triggering
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ping URLs
        run: |
          curl -s -o /dev/null https://magenta-bow-baroness.glitch.me/#/
          curl -s -o /dev/null https://magenta-bow-baroness.glitch.me/#/menu/esthers
          curl -s -o /dev/null https://magenta-bow-baroness.glitch.me/#/checkout
          curl -s -o /dev/null https://magenta-bow-baroness.glitch.me/#/checkout
